apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
    name: app-prod-issuer
    namespace: default
spec:
    acme:
# The ACME production api URL
        server: https://acme-v02.api.letsencrypt.org/directory
# Email address used for ACME registration
        email: ichopde@juniper.net
# Name of a secret used to store the ACME account private key
        privateKeySecretRef:
            name: app-prod-issuer-secret
# Enable the HTTP-01 challenge provider
        solvers:
        - http01:
            ingress:
                class: nginx